### ISSUE TITLE
Nearby: page updates

### ISSUE THREAD

**Issue by laidig** [camsys/onebusaway-nyc-atstop#15]
A list of things to do with the nearby branch before moving to master:
# on the template
1. Fix layout
2. In the list of arrivals for each stop, remove references to routes from stops for location   (use the atstopService results instead)
# Refactor atstop service to
## add optional group options:
1. no group
2. group by routes (current default)
3. group by route and direction
   Use option 3 for calls from nearby controller
# In the controller
1. refactor so that requests are only fired for stops newly added, rather than all of them.
2. add a timeout to reload every 30s. Don't worry about a reload button for now

**Comment by khfayzullaev** [comment]
Why do you want to **cache requests for 10s**? How will the changes affect the _AtStop_ page behavior?

**Comment by laidig** [comment]
should the existing tick function stay largely the same, it would cut down
on traffic in/out. If that controller is refactored to be more performant,
feel free to ignore.

**Comment by khfayzullaev** [comment]
Okay! Caching is implemented 089ef9d6548a2854c0f14490ce44e76f2ec2c33a. I see your point! Instead of blocking users to refresh, we can cache the requests :+1:

**Comment by laidig** [comment]
all of these are taken care of. starting a new ticket with final tweaks
