### ISSUE TITLE
Services: Replace DateTimeService and Moment with Humanize duration

### ISSUE THREAD

**Issue by laidig** [camsys/onebusaway-nyc-atstop#16]
We have two libraries that deal with times and essentially serve the same purpose. Since the circular timer depends on humanize-duration, it's probably best to get rid of Moment and the DateTimeService, used on the AtStop page for showing predictions.

**Comment by khfayzullaev** [comment]
I would keep _Moment.js_ for now.

As for the `DateTimeService` (https://github.com/camsys/onebusaway-nyc-atstop/blob/1b0443487ef5d47857bb745c300970ca20e71fc5/www/js/services.js#L624), we may re-write it to use _HumanizeDuration.js_.

_Moment.js_ has a bunch of functions that should be written from scratch in JavaScript. And _Moment.js_ is not the same as _HumanizeDuration.js_. The later one can be used primarily for converting inputs.

Moreover, we may need _Moment.js_ later for **Alerts**.

**Comment by laidig** [comment]
Good point on Moment. I'm still irked about having two bits of code that do the same thing, though ;)

**Comment by khfayzullaev** [comment]
Yes, we should use _HumanizeDuration.js_ for the following function https://github.com/camsys/onebusaway-nyc-atstop/blob/1b0443487ef5d47857bb745c300970ca20e71fc5/www/js/services.js#L626

**Comment by khfayzullaev** [comment]
Closing the issue because it has not had recent activity.
