### ISSUE TITLE
App: Multilingual support

### ISSUE THREAD

**Issue by laidig** [camsys/onebusaway-nyc-atstop#18]
I've been asked if the app is multilingual, which it currently is not

https://github.com/angular-translate/angular-translate seems like a pretty nifty thing to try out. 
First, all of the text would need to be found and marked up in English. 
Then, those bits of text would be abstracted into their own js file. That file would likely see a lot of contributions.
Finally, language support in HumanizeDuration should be activated.

**Comment by khfayzullaev** [comment]
:+1: Will work on it!

**Comment by khfayzullaev** [comment]
I have added the angular-translate library recently. Now, we need extend it. Check this 2f684a1036a3856521e4d4b8696f80cc47ae9383 out!

**Comment by laidig** [comment]
Can you make this change in a branch? It's going to need a bit work on the front end

-----Original Message-----

**Comment by khfayzullaev** [comment]
Here it is! https://github.com/camsys/onebusaway-nyc-atstop/tree/multilanguage

**Comment by khfayzullaev** [comment]
Closing the issue because it has not had recent activity.
