### ISSUE TITLE
Map: set a view to a specific (current) stop

### ISSUE THREAD

**Issue by khfayzullaev** [camsys/onebusaway-nyc-atstop#19]
We may use `setView()` instead of `fitBounds()` (https://github.com/camsys/onebusaway-nyc-atstop/blob/master/www/js/controllers.js#L560) on the Map page. I have read that users are confused a bit.

**Comment by laidig** [comment]
I'm not opposed, but the reason for fitbounds() on the route-map page (from the route) was that we don't exactly know where the center is. 

Where did you see the confusion?

**Comment by khfayzullaev** [comment]
Since we know _current stop_ which is one of the the elements inside the _stops_ array, we can `setView()` on that specific element. Something like this:

``` js
leafletData.getMap().then(function(map) {
    map.setView(stops['current_stop'], 15, {
        animate: true
    });
});
```

**Comment by laidig** [comment]
yes. Only if current stop exists though. If the user reached the page via
the route list, it won't be there.

Feel free to make the change!

**Comment by khfayzullaev** [comment]
Commit f926a1256ba21dab061a72aaed8f16ac012fe85e implements this very functionality.
