### ISSUE TITLE
iOS: map zoom in/out issue

### ISSUE THREAD

**Issue by khfayzullaev** [camsys/onebusaway-nyc-atstop#25]
I have noticed that the zoom in/out buttons are not working properly on the emulator. Does it work properly on a iOS device?

**Comment by laidig** [comment]
something odd is going on on the map page. even in the browser, zoomend/dragend events are not getting emitted properly. 

Meanwhile, the nearby page works just fine. Any ideas on your end? The event code is the same from what I can tell.

**Comment by khfayzullaev** [comment]
I had a chance to test it locally. I did not get any errors. It seems it conflicts with Ionic's methods. But, I am not sure since I cannot confirm that. So, nothing on my end.

**Comment by khfayzullaev** [comment]
@laidig any updates on this?

**Comment by laidig** [comment]
I spent a lot of time looking at this yesterday, and couldn't figure out why the events are only somewhat firing.

**Comment by khfayzullaev** [comment]
@laidig is this still an issue?

**Comment by laidig** [comment]
I have not been able to solve it.

**Comment by khfayzullaev** [comment]
Closing the issue because it has not had recent activity.
