### ISSUE TITLE
Zoom out when route on nearby page is clicked

### ISSUE THREAD

**Issue by laidig** [camsys/onebusaway-nyc-atstop#9]
The current zoom on the nearby page is pretty tight and does not change when clicked. 

If the latest angular-leaflet has a working setView(), use that to zoom out a level, showing the context for route.

**Comment by khfayzullaev** [comment]
Commit 17c870ca544397c962957e958c9627abcd89722a fixes the issue. The zoom level can be changed now, too.

`map.setView($scope.markers['currentStop'], 13, {animate: true});`
